// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {node} from '../models';

export function DialAddr(arg1:string):Promise<string>;

export function History(arg1:string):Promise<Array<node.Message>>;

export function ListAliases():Promise<Array<node.Alias>>;

export function ListPeers():Promise<Array<node.PeerInfo>>;

export function Ping(arg1:string):Promise<string>;

export function RemoveAlias(arg1:string):Promise<string>;

export function Scan(arg1:string):Promise<string>;

export function SelfPeerID():Promise<string>;

export function SendFile(arg1:string,arg2:string):Promise<string>;

export function SendText(arg1:string,arg2:string):Promise<string>;

export function SetAlias(arg1:string,arg2:string):Promise<string>;
