// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialAddr(arg1) {
  return window['go']['main']['App']['DialAddr'](arg1);
}

export function History(arg1) {
  return window['go']['main']['App']['History'](arg1);
}

export function ListAliases() {
  return window['go']['main']['App']['ListAliases']();
}

export function ListPeers() {
  return window['go']['main']['App']['ListPeers']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function RemoveAlias(arg1) {
  return window['go']['main']['App']['RemoveAlias'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SelfPeerID() {
  return window['go']['main']['App']['SelfPeerID']();
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetAlias(arg1, arg2) {
  return window['go']['main']['App']['SetAlias'](arg1, arg2);
}
